### PR TITLE
Allow a wrapper cookbook to specify a local template, delay reloading the main process

### PR DESCRIPTION
**Pull request by jorhett**
This change allows a wrapper cookbook to specify a local template for their own custom config.

### CODE REVIEW

**Comment by jorhett** [comment]
Also skip installing the repo since amazon versions aren't listed there, and td-agent is available in the amazon repos.

**Comment by jorhett** [comment]
Also delayed the reload action so that a wrapper which is installing conf.d configs can also notify process and it reloads a single time.

**Comment by yyuu** [comment]
tenplate_cookbook looks nice. Though I need to verify other features if their assumption is true. Please split PR into multiple pieces per feature, then I can merge one by one.

**Comment by jorhett** [comment]
They are one line changes. You really want me to create three separate branches for one line of code each?

On October 22, 2015 3:08:28 PM PDT, "Yamashita, Yuu" <notifications@github.com> wrote:
>tenplate_cookbook looks nice. Though I need to verify other features if
>their assumption is true. Please split PR into multiple pieces per
>feature, then I can merge one by one.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/treasure-data/chef-td-agent/pull/66#issuecomment-150369813

-- 
... from the phone of Jo Rhett
Cell: +1 (415) 999-1798

**Comment by yyuu** [comment]
One per feature would be idealistic. At least please split PR for Amazon Linux issue.

**Comment by jorhett** [comment]
I am going to do this, but understand that this is 12 commands and a few hundred words to create each branch and do each commit, and most of these branches aren't even 12 characters different. This is  busywork assignments for me, when I'm providing value back to you.

**Comment by jorhett** [comment]
Removed the amazon linux change.

**Comment by jorhett** [comment]
starting over

**Pull request closed without merging**
